# Generated by Django 5.2 on 2025-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_brainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainimage',
            name='address',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='brainimage',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='brainimage',
            name='city',
            field=models.CharField(blank='true', max_length=100),
        ),
        migrations.AddField(
            model_name='brainimage',
            name='first_name',
            field=models.CharField(blank='true', max_length=100),
        ),
        migrations.AddField(
            model_name='brainimage',
            name='last_name',
            field=models.CharField(blank='true', max_length=100),
        ),
        migrations.AddField(
            model_name='brainimage',
            name='zip_code',
            field=models.CharField(blank='true', max_length=6),
        ),
    ]
