# Generated by Django 5.2 on 2025-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_brainimage_address_brainimage_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainimage',
            name='address2',
            field=models.CharField(blank='true', max_length=200),
        ),
    ]
